// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uakqylxirvfhmsbanuzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVha3F5bHhpcnZmaG1zYmFudXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxMDY3MzIsImV4cCI6MjA5MDY4MjczMn0.V46OdYVjAQ6XybxQTk8vqMQVqg3Y9m_lg3sQ1AwmsD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});